import React, { useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
    faInfoCircle,
    faCommentDots,
    faCheck,
    faTimes,
    faTag,
    faPlus,
    faFileAlt,
    faLink,
    faAlignLeft,
    faFolder,
    faImage,
    faUpload,
    faUser,
    faTrash,
    faClock
} from '@fortawesome/free-solid-svg-icons';
import { useTranslation } from 'react-i18next';
import './basicSection.css';
import { useAuthContext } from '../../../../contexts/UserContext';

const BasicInfoSection = ({
    values,
    onChangeHandler,
    setValues,
    generateSlug,
    newTag,
    setNewTag,
    addTag,
    removeTag,
    handleMainImageUpload,
    addMainImageFromUrl,
    removeMainImage,
    updateMainImageAlt,
    updateMainImageCaption
}) => {
    const { t } = useTranslation('content');
    const { userEmail, username } = useAuthContext(); // Get user info

    // Add state for main image URL input
    const [showMainImageUrlInput, setShowMainImageUrlInput] = useState(false);
    const [mainImageUrl, setMainImageUrl] = useState('');

    const handleKeyPress = (e) => {
        if (e.key === 'Enter') {
            e.preventDefault();
            addTag();
        }
    };

    // Get author name for preview
    const getAuthorName = () => {
        if (!values.showAuthor) return null; // If checkbox is unchecked, no author
        return username || userEmail || 'Anonymous';
    };

    return (
        <div className="publication-form-section-card">
            <div className="publication-form-section-header">
                <h2 className="publication-form-section-title">
                    <FontAwesomeIcon icon={faInfoCircle} />
                    {t('publications.sections.basicInfo')}
                </h2>
            </div>

            <div className="publication-form-section-content">
                {/* Title */}
                <div className="publication-form-group">
                    <label htmlFor="title" className="publication-field-label">
                        <FontAwesomeIcon icon={faFileAlt} />
                        {t('publications.basic.title')}
                        <span className="publication-required-indicator">*</span>
                    </label>
                    <input
                        type="text"
                        id="title"
                        name="title"
                        value={values.title}
                        onChange={onChangeHandler}
                        placeholder={t('publications.basic.titlePlaceholder')}
                        required
                    />
                </div>

                {/* Slug - Read Only */}
                <div className="publication-form-group">
                    <label htmlFor="slug" className="publication-field-label">
                        <FontAwesomeIcon icon={faLink} />
                        {t('publications.basic.slug')}
                        <span className="publication-required-indicator">*</span>
                    </label>
                    <input
                        type="text"
                        id="slug"
                        name="slug"
                        value={values.slug}
                        readOnly
                        disabled
                        className="publication-readonly-field"
                    />
                    <div className="publication-field-hint">
                        {t('publications.basic.slugAutoGenerated')}
                    </div>
                </div>

                {/* Short Description */}
                <div className="publication-form-group">
                    <label htmlFor="shortDescription" className="publication-field-label">
                        <FontAwesomeIcon icon={faAlignLeft} />
                        {t('publications.basic.shortDescription')}
                        <span className="publication-required-indicator">*</span>
                    </label>
                    <textarea
                        id="shortDescription"
                        name="shortDescription"
                        value={values.shortDescription}
                        onChange={onChangeHandler}
                        placeholder={t('publications.basic.shortDescriptionPlaceholder')}
                        rows="3"
                        required
                    />
                </div>

                {/* Main Image */}
                <div className="publication-form-group">
                    <label>
                        <FontAwesomeIcon icon={faImage} />
                        <span style={{ marginLeft: '0.5rem' }}>
                            {t('publications.media.mainImage')}
                        </span>
                    </label>
                    <div className="publication-sections-field-help">
                        {t('publications.helpTexts.sectionImageHelp')}
                    </div>

                    <div className="publication-sections-image-upload">
                        {/* Upload methods */}
                        <div className="publication-sections-upload-methods">
                            <div className="publication-sections-upload-method">
                                <label className="publication-sections-upload-btn">
                                    <FontAwesomeIcon icon={faUpload} />
                                    {values.mainImage?.src ? t('publications.media.changeImage') : t('publications.media.uploadImage')}
                                    <input
                                        type="file"
                                        accept="image/*"
                                        onChange={handleMainImageUpload}
                                        style={{ display: 'none' }}
                                    />
                                </label>
                            </div>

                            <div className="publication-sections-upload-method">
                                <button
                                    type="button"
                                    className="publication-sections-upload-btn"
                                    onClick={() => setShowMainImageUrlInput(prev => !prev)}
                                >
                                    <FontAwesomeIcon icon={faLink} />
                                    {values.mainImage?.src ? t('publications.media.changeImageUrl') : t('publications.media.addImageUrl')}
                                </button>
                            </div>

                            {values.mainImage?.src && (
                                <div className="publication-sections-upload-method">
                                    <button
                                        type="button"
                                        className="publication-sections-clear-btn"
                                        onClick={removeMainImage}
                                    >
                                        <FontAwesomeIcon icon={faTrash} />
                                        {t('publications.media.clearImage')}
                                    </button>
                                </div>
                            )}
                        </div>

                        {/* URL input section */}
                        {showMainImageUrlInput && (
                            <div className="publication-sections-url-input-section">
                                <input
                                    type="url"
                                    placeholder={t('publications.media.imageUrl')}
                                    value={mainImageUrl || ''}
                                    onChange={(e) => setMainImageUrl(e.target.value)}
                                    className="publication-sections-url-input"
                                />
                                <button
                                    type="button"
                                    className="publication-sections-url-add-btn"
                                    onClick={() => {
                                        if (mainImageUrl?.trim()) {
                                            addMainImageFromUrl(mainImageUrl.trim());
                                            setMainImageUrl('');
                                            setShowMainImageUrlInput(false);
                                        }
                                    }}
                                    disabled={!mainImageUrl?.trim()}
                                >
                                    <FontAwesomeIcon icon={faLink} />
                                    {t('publications.media.addImage')}
                                </button>
                            </div>
                        )}
                    </div>

                    {/* Single Image Preview with controls on the right */}
                    {values.mainImage?.src && (
                        <div className="publication-sections-image-preview">
                            <div className="publication-sections-image-container">
                                <div className="publication-sections-image-item">
                                    <div className="publication-sections-image-preview">
                                        <img src={values.mainImage.src} alt={values.mainImage.alt || 'Main image'} />
                                        <div className="publication-sections-image-overlay">
                                            <button
                                                type="button"
                                                className="publication-sections-image-remove-btn"
                                                onClick={removeMainImage}
                                                title={t('publications.media.removeImage')}
                                            >
                                                <FontAwesomeIcon icon={faTrash} />
                                            </button>
                                        </div>
                                        {values.mainImage.isUploading && (
                                            <div className="publication-sections-image-uploading">
                                                <div className="publication-sections-uploading-spinner"></div>
                                            </div>
                                        )}
                                    </div>
                                </div>

                                {/* Controls on the right side */}
                                <div className="publication-sections-image-controls">
                                    <div className="publication-sections-image-input-group">
                                        <label>{t('publications.media.altText')}:</label>
                                        <input
                                            type="text"
                                            placeholder={t('publications.media.imageDescription')}
                                            value={values.mainImage.alt || ''}
                                            onChange={(e) => updateMainImageAlt(e.target.value)}
                                            className="publication-sections-image-input"
                                            maxLength={100}
                                        />
                                        <div className="publication-sections-char-count">
                                            {values.mainImage.alt?.length || 0}/100
                                        </div>
                                    </div>

                                    <div className="publication-sections-image-input-group">
                                        <label>{t('publications.media.caption')}:</label>
                                        <input
                                            type="text"
                                            placeholder={t('publications.media.imageCaption')}
                                            value={values.mainImage.caption || ''}
                                            onChange={(e) => updateMainImageCaption(e.target.value)}
                                            className="publication-sections-image-input"
                                            maxLength={150}
                                        />
                                        <div className="publication-sections-char-count">
                                            {values.mainImage.caption?.length || 0}/150
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    )}
                </div>

                {/* Category */}
                <div className="publication-form-group">
                    <label htmlFor="category" className="publication-field-label">
                        <FontAwesomeIcon icon={faFolder} />
                        {t('publications.basic.category')}
                    </label>
                    <select
                        id="category"
                        name="category"
                        value={values.category}
                        onChange={onChangeHandler}
                    >
                        <option value="">{t('publications.basic.selectCategory')}</option>
                        {/* Update the category options to use the new categories */}
                        <option value="technology">{t('publications.categories.technology')}</option>
                        <option value="health">{t('publications.categories.health')}</option>
                        <option value="lifestyle">{t('publications.categories.lifestyle')}</option>
                        <option value="education">{t('publications.categories.education')}</option>
                        <option value="community">{t('publications.categories.community')}</option>
                        <option value="other">{t('publications.categories.other')}</option>
                    </select>
                </div>

                {/* Read Time */}
                <div className="publication-form-group">
                    <label htmlFor="readTime" className="publication-field-label">
                        <FontAwesomeIcon icon={faClock} />
                        {t('publications.basic.readTime')}
                    </label>
                    <input
                        type="number"
                        id="readTime"
                        name="readTime"
                        value={values.readTime}
                        onChange={onChangeHandler}
                        placeholder={t('publications.basic.readTimePlaceholder')}
                    />
                </div>

                {/* Tags */}
                <div className="publication-form-group">
                    <label htmlFor="tags" className="publication-field-label">
                        <FontAwesomeIcon icon={faTag} />
                        {t('publications.basic.tags')}
                    </label>
                    <div className="publication-tags-container">
                        <div className="publication-tags-input-group">
                            <input
                                type="text"
                                value={newTag}
                                onChange={(e) => setNewTag(e.target.value)}
                                onKeyPress={handleKeyPress}
                                placeholder={t('publications.basic.addTagPlaceholder')}
                                className="publication-tags-input"
                            />
                            <button
                                type="button"
                                onClick={addTag}
                                className="publication-tags-add-btn"
                                disabled={!newTag.trim()}
                            >
                                <FontAwesomeIcon icon={faPlus} />
                            </button>
                        </div>
                        <div className="publication-tags-list">
                            {values.tags.map((tag, index) => (
                                <span key={index} className="publication-tag">
                                    {tag}
                                    <button
                                        type="button"
                                        onClick={() => removeTag(tag)}
                                        className="publication-tag-remove"
                                    >
                                        ×
                                    </button>
                                </span>
                            ))}
                        </div>
                    </div>
                </div>

                {/* Comments and Author Toggles - Side by Side */}
                <div className="publication-form-group">
                    <div className="publication-toggles-container">
                        {/* Comments Enabled */}
                        <div className="publication-toggle-item">
                            <div className="publication-comments-enabled-section">
                                <div className="publication-comments-enabled-header">
                                    <label className="publication-comments-enabled-label">
                                        <FontAwesomeIcon icon={faCommentDots} />
                                        {t('publications.settings.commentsEnabled')}
                                    </label>
                                    <div className="publication-comments-enabled-description">
                                        {t('publications.settings.commentsEnabledDescription')}
                                    </div>
                                </div>

                                <div className="publication-comments-toggle-container">
                                    <label className="publication-comments-toggle">
                                        <input
                                            type="checkbox"
                                            name="commentsEnabled"
                                            checked={values.commentsEnabled}
                                            onChange={onChangeHandler}
                                            className="publication-comments-toggle-input"
                                        />
                                        <span className="publication-comments-toggle-slider">
                                            <span className="publication-comments-toggle-thumb">
                                                <FontAwesomeIcon
                                                    icon={values.commentsEnabled ? faCheck : faTimes}
                                                    className="publication-comments-toggle-icon"
                                                />
                                            </span>
                                        </span>
                                        <span className="publication-comments-toggle-text">
                                            {values.commentsEnabled ? t('publications.settings.commentsAllowed') : t('publications.settings.commentsDisabled')}
                                        </span>
                                    </label>
                                </div>
                            </div>
                        </div>

                        {/* Show Author */}
                        <div className="publication-toggle-item">
                            <div className="publication-comments-enabled-section">
                                <div className="publication-comments-enabled-header">
                                    <label className="publication-comments-enabled-label">
                                        <FontAwesomeIcon icon={faUser} />
                                        {t('publications.basic.showAuthor')}
                                    </label>
                                    <div className="publication-comments-enabled-description">
                                        {t('publications.basic.showAuthorDescription')}
                                    </div>
                                </div>

                                <div className="publication-comments-toggle-container">
                                    <label className="publication-comments-toggle">
                                        <input
                                            type="checkbox"
                                            name="showAuthor"
                                            checked={values.showAuthor}
                                            onChange={onChangeHandler}
                                            className="publication-comments-toggle-input"
                                        />
                                        <span className="publication-comments-toggle-slider">
                                            <span className="publication-comments-toggle-thumb">
                                                <FontAwesomeIcon
                                                    icon={values.showAuthor ? faCheck : faTimes}
                                                    className="publication-comments-toggle-icon"
                                                />
                                            </span>
                                        </span>
                                        <span className="publication-comments-toggle-text">
                                            {values.showAuthor ? t('publications.basic.authorVisible') : t('publications.basic.authorHidden')}
                                        </span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default BasicInfoSection;
