import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faInfoCircle } from '@fortawesome/free-solid-svg-icons';
import { useTranslation } from 'react-i18next';
import './basicSection.css';

const BasicInfoSection = ({ values, onChangeHandler, setValues, generateSlug }) => {
    const { t } = useTranslation();

    return (
        <div className="publication-form-section-card">
            <div className="publication-form-section-header">
                <h2 className="publication-form-section-title">
                    <FontAwesomeIcon icon={faInfoCircle} />
                    {t('publications.sections.basicInfo')}
                </h2>
            </div>

            <div className="publication-form-section-content">
                {/* Title */}
                <div className="publication-form-group">
                    <label htmlFor="title">
                        {t('publications.fields.title')}
                        <span className="publication-required-indicator">*</span>
                    </label>
                    <input
                        type="text"
                        id="title"
                        name="title"
                        value={values.title}
                        onChange={onChangeHandler}
                        placeholder={t('publications.fields.titlePlaceholder')}
                        required
                    />
                </div>

                {/* Slug - Read Only */}
                <div className="publication-form-group">
                    <label htmlFor="slug">
                        {t('publications.fields.slug')}
                        <span className="publication-required-indicator">*</span>
                    </label>
                    <input
                        type="text"
                        id="slug"
                        name="slug"
                        value={values.slug}
                        readOnly
                        disabled
                        className="publication-input-disabled"
                    />
                    <div className="publication-field-help">
                        {t('publications.fields.slugAutoGenerated')}
                    </div>
                </div>

                {/* Short Description */}
                <div className="publication-form-group">
                    <label htmlFor="shortDescription">
                        {t('publications.fields.shortDescription')}
                    </label>
                    <textarea
                        id="shortDescription"
                        name="shortDescription"
                        value={values.shortDescription}
                        onChange={onChangeHandler}
                        placeholder={t('publications.fields.shortDescriptionPlaceholder')}
                        rows="3"
                    />
                </div>

                {/* Category */}
                <div className="publication-form-group">
                    <label htmlFor="category">
                        {t('publications.fields.category')}
                    </label>
                    <select
                        id="category"
                        name="category"
                        value={values.category}
                        onChange={onChangeHandler}
                    >
                        <option value="">{t('publications.fields.selectCategory')}</option>
                        <option value="technology">{t('publications.categories.technology')}</option>
                        <option value="health">{t('publications.categories.health')}</option>
                        <option value="education">{t('publications.categories.education')}</option>
                        <option value="lifestyle">{t('publications.categories.lifestyle')}</option>
                        <option value="other">{t('publications.categories.other')}</option>
                    </select>
                </div>
            </div>
        </div>
    );
};

export default BasicInfoSection;
