import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
    faInfoCircle,
    faCommentDots,
    faCheck,
    faTimes,
    faTag,
    faPlus,
    faFileAlt,
    faLink,
    faAlignLeft,
    faFolder,
    faImage,
    faUpload
} from '@fortawesome/free-solid-svg-icons';
import { useTranslation } from 'react-i18next';
import './basicSection.css';

const BasicInfoSection = ({
    values,
    onChangeHandler,
    setValues,
    generateSlug,
    newTag,
    setNewTag,
    addTag,
    removeTag,
    handleMainImageUpload,
    addMainImageFromUrl,
    removeMainImage,
    updateMainImageAlt,
    updateMainImageCaption
}) => {
    const { t } = useTranslation();

    const handleKeyPress = (e) => {
        if (e.key === 'Enter') {
            e.preventDefault();
            addTag();
        }
    };

    return (
        <div className="publication-form-section-card">
            <div className="publication-form-section-header">
                <h2 className="publication-form-section-title">
                    <FontAwesomeIcon icon={faInfoCircle} />
                    {t('publications.sections.basicInfo')}
                </h2>
            </div>

            <div className="publication-form-section-content">
                {/* Title */}
                <div className="publication-form-group">
                    <label htmlFor="title" className="publication-field-label">
                        <FontAwesomeIcon icon={faFileAlt} />
                        {t('publications.fields.title')}
                        <span className="publication-required-indicator">*</span>
                    </label>
                    <input
                        type="text"
                        id="title"
                        name="title"
                        value={values.title}
                        onChange={onChangeHandler}
                        placeholder={t('publications.fields.titlePlaceholder')}
                        required
                    />
                </div>

                {/* Slug - Read Only */}
                <div className="publication-form-group">
                    <label htmlFor="slug" className="publication-field-label">
                        <FontAwesomeIcon icon={faLink} />
                        {t('publications.fields.slug')}
                        <span className="publication-required-indicator">*</span>
                    </label>
                    <input
                        type="text"
                        id="slug"
                        name="slug"
                        value={values.slug}
                        readOnly
                        disabled
                        className="publication-input-disabled"
                    />
                    <div className="publication-field-help">
                        {t('publications.fields.slugAutoGenerated')}
                    </div>
                </div>

                {/* Short Description */}
                <div className="publication-form-group">
                    <label htmlFor="shortDescription" className="publication-field-label">
                        <FontAwesomeIcon icon={faAlignLeft} />
                        {t('publications.fields.shortDescription')}
                    </label>
                    <textarea
                        id="shortDescription"
                        name="shortDescription"
                        value={values.shortDescription}
                        onChange={onChangeHandler}
                        placeholder={t('publications.fields.shortDescriptionPlaceholder')}
                        rows="3"
                    />
                </div>

                {/* Main Image */}
                <div className="publication-form-group">
                    <label className="publication-field-label">
                        <FontAwesomeIcon icon={faImage} />
                        {t('publications.fields.mainImage') || 'Main Image'}
                    </label>

                    <div className="publication-main-image-section">
                        {/* Image Upload */}
                        <div className="publication-main-image-upload">
                            <input
                                type="file"
                                accept="image/*"
                                onChange={handleMainImageUpload}
                                className="publication-main-image-input"
                                id="main-image-upload"
                            />
                            <label htmlFor="main-image-upload" className="publication-main-image-upload-btn">
                                <FontAwesomeIcon icon={faUpload} />
                                {values.mainImage?.src ? t('publications.create.changeImage') || 'Change Image' : t('publications.create.uploadImage') || 'Upload Image'}
                            </label>
                        </div>

                        {/* Image Preview */}
                        {values.mainImage?.src && (
                            <div className="publication-main-image-preview">
                                <div className="publication-main-image-container">
                                    <img
                                        src={values.mainImage.src}
                                        alt={values.mainImage.alt || 'Main image preview'}
                                        className="publication-main-image"
                                    />
                                    <button
                                        type="button"
                                        onClick={removeMainImage}
                                        className="publication-main-image-remove"
                                        title={t('publications.create.removeImage') || 'Remove Image'}
                                    >
                                        <FontAwesomeIcon icon={faTimes} />
                                    </button>
                                </div>

                                {/* Image Details */}
                                <div className="publication-main-image-details">
                                    <div className="publication-form-group">
                                        <label className="publication-field-label">
                                            {t('publications.fields.imageAlt') || 'Image Alt Text'}
                                        </label>
                                        <input
                                            type="text"
                                            value={values.mainImage.alt || ''}
                                            onChange={(e) => updateMainImageAlt(e.target.value)}
                                            placeholder={t('publications.fields.imageAltPlaceholder') || 'Describe the image for accessibility'}
                                            className="publication-input"
                                        />
                                    </div>

                                    <div className="publication-form-group">
                                        <label className="publication-field-label">
                                            {t('publications.fields.imageCaption') || 'Image Caption'}
                                        </label>
                                        <input
                                            type="text"
                                            value={values.mainImage.caption || ''}
                                            onChange={(e) => updateMainImageCaption(e.target.value)}
                                            placeholder={t('publications.fields.imageCaptionPlaceholder') || 'Optional caption for the image'}
                                            className="publication-input"
                                        />
                                    </div>
                                </div>
                            </div>
                        )}

                        {/* URL Input */}
                        <div className="publication-main-image-url">
                            <div className="publication-main-image-url-input">
                                <input
                                    type="url"
                                    placeholder={t('publications.fields.imageUrlPlaceholder') || 'Or enter image URL'}
                                    className="publication-input"
                                    onKeyPress={(e) => {
                                        if (e.key === 'Enter') {
                                            e.preventDefault();
                                            addMainImageFromUrl(e.target.value);
                                            e.target.value = '';
                                        }
                                    }}
                                />
                                <button
                                    type="button"
                                    onClick={(e) => {
                                        const input = e.target.previousElementSibling;
                                        addMainImageFromUrl(input.value);
                                        input.value = '';
                                    }}
                                    className="publication-main-image-url-btn"
                                >
                                    <FontAwesomeIcon icon={faLink} />
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Category */}
                <div className="publication-form-group">
                    <label htmlFor="category" className="publication-field-label">
                        <FontAwesomeIcon icon={faFolder} />
                        {t('publications.fields.category')}
                    </label>
                    <select
                        id="category"
                        name="category"
                        value={values.category}
                        onChange={onChangeHandler}
                    >
                        <option value="">{t('publications.fields.selectCategory')}</option>
                        <option value="technology">{t('publications.categories.technology')}</option>
                        <option value="health">{t('publications.categories.health')}</option>
                        <option value="education">{t('publications.categories.education')}</option>
                        <option value="lifestyle">{t('publications.categories.lifestyle')}</option>
                        <option value="other">{t('publications.categories.other')}</option>
                    </select>
                </div>

                {/* Tags */}
                <div className="publication-form-group">
                    <label htmlFor="tags" className="publication-field-label">
                        <FontAwesomeIcon icon={faTag} />
                        {t('publications.fields.tags')}
                    </label>
                    <div className="publication-tags-container">
                        <div className="publication-tags-input-group">
                            <input
                                type="text"
                                value={newTag}
                                onChange={(e) => setNewTag(e.target.value)}
                                onKeyPress={handleKeyPress}
                                placeholder={t('publications.fields.addTagPlaceholder')}
                                className="publication-tags-input"
                            />
                            <button
                                type="button"
                                onClick={addTag}
                                className="publication-tags-add-btn"
                                disabled={!newTag.trim()}
                            >
                                <FontAwesomeIcon icon={faPlus} />
                            </button>
                        </div>
                        <div className="publication-tags-list">
                            {values.tags.map((tag, index) => (
                                <span key={index} className="publication-tag">
                                    {tag}
                                    <button
                                        type="button"
                                        onClick={() => removeTag(tag)}
                                        className="publication-tag-remove"
                                    >
                                        ×
                                    </button>
                                </span>
                            ))}
                        </div>
                    </div>
                </div>

                {/* Comments Enabled */}
                <div className="publication-form-group">
                    <div className="publication-comments-enabled-section">
                        <div className="publication-comments-enabled-header">
                            <label className="publication-comments-enabled-label">
                                <FontAwesomeIcon icon={faCommentDots} />
                                {t('publications.commentsEnabled')}
                            </label>
                            <div className="publication-comments-enabled-description">
                                {t('publications.commentsEnabledDescription')}
                            </div>
                        </div>

                        <div className="publication-comments-toggle-container">
                            <label className="publication-comments-toggle">
                                <input
                                    type="checkbox"
                                    name="commentsEnabled"
                                    checked={values.commentsEnabled}
                                    onChange={onChangeHandler}
                                    className="publication-comments-toggle-input"
                                />
                                <span className="publication-comments-toggle-slider">
                                    <span className="publication-comments-toggle-thumb">
                                        <FontAwesomeIcon
                                            icon={values.commentsEnabled ? faCheck : faTimes}
                                            className="publication-comments-toggle-icon"
                                        />
                                    </span>
                                </span>
                                <span className="publication-comments-toggle-text">
                                    {values.commentsEnabled
                                        ? t('publications.commentsAllowed')
                                        : t('publications.commentsDisabled')
                                    }
                                </span>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default BasicInfoSection;
