import React, { useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
    faInfoCircle,
    faCommentDots,
    faCheck,
    faTimes,
    faTag,
    faPlus,
    faFileAlt,
    faLink,
    faAlignLeft,
    faFolder,
    faImage,
    faUpload,
    faUser,
    faTrash,
    faClock
} from '@fortawesome/free-solid-svg-icons';
import { useTranslation } from 'react-i18next';
import './basicSection.css';
import { useAuthContext } from '../../../../contexts/UserContext';

const BasicInfoSection = ({
    values,
    onChangeHandler,
    setValues,
    generateSlug,
    newTag,
    setNewTag,
    addTag,
    removeTag,
    handleMainImageUpload,
    addMainImageFromUrl,
    removeMainImage,
    updateMainImageAlt,
    updateMainImageCaption,
    handleAuthorImageUpload,
    addAuthorImageFromUrl,
    removeAuthorImage,
    updateAuthorImageAlt,
    updateAuthorImageCaption
}) => {
    const { t } = useTranslation();
    const { userEmail, username } = useAuthContext();

    // Add state for main image URL input
    const [showMainImageUrlInput, setShowMainImageUrlInput] = useState(false);
    const [mainImageUrl, setMainImageUrl] = useState('');

    // Add state for author image URL input
    const [showAuthorImageUrlInput, setShowAuthorImageUrlInput] = useState(false);
    const [authorImageUrl, setAuthorImageUrl] = useState('');

    const handleKeyPress = (e) => {
        if (e.key === 'Enter') {
            e.preventDefault();
            addTag();
        }
    };

    // Get author name for preview
    const getAuthorName = () => {
        if (!values.showAuthor) return null;
        return username || userEmail || 'Anonymous';
    };

    return (
        <div className="publication-form-section-card">
            <div className="publication-form-section-header">
                <h2 className="publication-form-section-title">
                    <FontAwesomeIcon icon={faInfoCircle} />
                    {t('stories.sections.basicInfo')}
                </h2>
            </div>

            <div className="publication-form-section-content">
                {/* Title */}
                <div className="publication-form-group">
                    <label htmlFor="title" className="publication-field-label">
                        <FontAwesomeIcon icon={faFileAlt} />
                        {t('stories.basic.title')}
                        <span className="publication-required-indicator">*</span>
                    </label>
                    <input
                        type="text"
                        id="title"
                        name="title"
                        value={values.title}
                        onChange={onChangeHandler}
                        placeholder={t('stories.basic.titlePlaceholder')}
                        required
                    />
                </div>

                {/* Slug - Read Only */}
                <div className="publication-form-group">
                    <label htmlFor="slug" className="publication-field-label">
                        <FontAwesomeIcon icon={faLink} />
                        {t('stories.basic.slug')}
                        <span className="publication-required-indicator">*</span>
                    </label>
                    <input
                        type="text"
                        id="slug"
                        name="slug"
                        value={values.slug}
                        readOnly
                        disabled
                        className="publication-readonly-field"
                    />
                    <div className="publication-field-hint">
                        {t('stories.basic.slugAutoGenerated')}
                    </div>
                </div>

                {/* Short Description */}
                <div className="publication-form-group">
                    <label htmlFor="shortDescription" className="publication-field-label">
                        <FontAwesomeIcon icon={faAlignLeft} />
                        {t('stories.basic.shortDescription')}
                        <span className="publication-required-indicator">*</span>
                    </label>
                    <textarea
                        id="shortDescription"
                        name="shortDescription"
                        value={values.shortDescription}
                        onChange={onChangeHandler}
                        placeholder={t('stories.basic.shortDescriptionPlaceholder')}
                        rows="3"
                        required
                    />
                </div>

                {/* Main Image */}
                <div className="publication-form-group">
                    <label>
                        <FontAwesomeIcon icon={faImage} />
                        <span style={{ marginLeft: '0.5rem' }}>
                            {t('stories.media.mainImage')}
                        </span>
                    </label>
                    <div className="publication-sections-field-help">
                        {t('stories.helpTexts.sectionImageHelp')}
                    </div>

                    <div className="publication-sections-image-upload">
                        {/* Upload methods */}
                        <div className="publication-sections-upload-methods">
                            <div className="publication-sections-upload-method">
                                <label className="publication-sections-upload-btn">
                                    <FontAwesomeIcon icon={faUpload} />
                                    {values.mainImage?.src ? t('stories.media.changeImage') : t('stories.media.uploadImage')}
                                    <input
                                        type="file"
                                        accept="image/*"
                                        onChange={handleMainImageUpload}
                                        style={{ display: 'none' }}
                                    />
                                </label>
                            </div>

                            <div className="publication-sections-upload-method">
                                <button
                                    type="button"
                                    className="publication-sections-upload-btn"
                                    onClick={() => setShowMainImageUrlInput(prev => !prev)}
                                >
                                    <FontAwesomeIcon icon={faLink} />
                                    {values.mainImage?.src ? t('stories.media.changeImageUrl') : t('stories.media.addImageUrl')}
                                </button>
                            </div>

                            {values.mainImage?.src && (
                                <div className="publication-sections-upload-method">
                                    <button
                                        type="button"
                                        className="publication-sections-clear-btn"
                                        onClick={removeMainImage}
                                    >
                                        <FontAwesomeIcon icon={faTrash} />
                                        {t('stories.media.clearImage')}
                                    </button>
                                </div>
                            )}
                        </div>

                        {/* URL input section */}
                        {showMainImageUrlInput && (
                            <div className="publication-sections-url-input-section">
                                <input
                                    type="url"
                                    placeholder={t('stories.media.imageUrl')}
                                    value={mainImageUrl || ''}
                                    onChange={(e) => setMainImageUrl(e.target.value)}
                                    className="publication-sections-url-input"
                                />
                                <button
                                    type="button"
                                    className="publication-sections-url-add-btn"
                                    onClick={() => {
                                        if (mainImageUrl?.trim()) {
                                            addMainImageFromUrl(mainImageUrl.trim());
                                            setMainImageUrl('');
                                            setShowMainImageUrlInput(false);
                                        }
                                    }}
                                    disabled={!mainImageUrl?.trim()}
                                >
                                    <FontAwesomeIcon icon={faLink} />
                                    {t('stories.media.addImage')}
                                </button>
                            </div>
                        )}
                    </div>

                    {/* Single Image Preview with controls on the right */}
                    {values.mainImage?.src && (
                        <div className="publication-sections-image-preview">
                            <div className="publication-sections-image-container">
                                <div className="publication-sections-image-item">
                                    <div className="publication-sections-image-preview">
                                        <img src={values.mainImage.src} alt={values.mainImage.alt || 'Main image'} />
                                        <div className="publication-sections-image-overlay">
                                            <button
                                                type="button"
                                                className="publication-sections-image-remove-btn"
                                                onClick={removeMainImage}
                                                title={t('stories.media.removeImage')}
                                            >
                                                <FontAwesomeIcon icon={faTrash} />
                                            </button>
                                        </div>
                                        {values.mainImage.isUploading && (
                                            <div className="publication-sections-image-uploading">
                                                <div className="publication-sections-uploading-spinner"></div>
                                            </div>
                                        )}
                                    </div>
                                </div>

                                {/* Controls on the right side */}
                                <div className="publication-sections-image-controls">
                                    <div className="publication-sections-image-input-group">
                                        <label>{t('stories.media.altText')}:</label>
                                        <input
                                            type="text"
                                            placeholder={t('stories.media.imageDescription')}
                                            value={values.mainImage.alt || ''}
                                            onChange={(e) => updateMainImageAlt(e.target.value)}
                                            className="publication-sections-image-input"
                                            maxLength={100}
                                        />
                                        <div className="publication-sections-char-count">
                                            {values.mainImage.alt?.length || 0}/100
                                        </div>
                                    </div>

                                    <div className="publication-sections-image-input-group">
                                        <label>{t('stories.media.caption')}:</label>
                                        <input
                                            type="text"
                                            placeholder={t('stories.media.imageCaption')}
                                            value={values.mainImage.caption || ''}
                                            onChange={(e) => updateMainImageCaption(e.target.value)}
                                            className="publication-sections-image-input"
                                            maxLength={150}
                                        />
                                        <div className="publication-sections-char-count">
                                            {values.mainImage.caption?.length || 0}/150
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    )}
                </div>

                {/* Category - Stories specific categories */}
                <div className="publication-form-group">
                    <label htmlFor="category" className="publication-field-label">
                        <FontAwesomeIcon icon={faFolder} />
                        {t('stories.basic.category')}
                    </label>
                    <select
                        id="category"
                        name="category"
                        value={values.category}
                        onChange={onChangeHandler}
                    >
                        <option value="">{t('stories.basic.selectCategory')}</option>
                        <option value="personal">{t('stories.categories.personal')}</option>
                        <option value="community">{t('stories.categories.community')}</option>
                        <option value="educational">{t('stories.categories.educational')}</option>
                        <option value="inspirational">{t('stories.categories.inspirational')}</option>
                        <option value="case-study">{t('stories.categories.caseStudy')}</option>
                        <option value="testimonial">{t('stories.categories.testimonial')}</option>
                        <option value="other">{t('stories.categories.other')}</option>
                    </select>
                </div>

                {/* Read Time */}
                <div className="publication-form-group">
                    <label htmlFor="readTime" className="publication-field-label">
                        <FontAwesomeIcon icon={faClock} />
                        {t('stories.basic.readTime')}
                    </label>
                    <input
                        type="number"
                        id="readTime"
                        name="readTime"
                        value={values.readTime}
                        onChange={onChangeHandler}
                        placeholder={t('stories.basic.readTimePlaceholder')}
                    />
                </div>

                {/* Tags */}
                <div className="publication-form-group">
                    <label htmlFor="tags" className="publication-field-label">
                        <FontAwesomeIcon icon={faTag} />
                        {t('stories.basic.tags')}
                    </label>
                    <div className="publication-tags-container">
                        <div className="publication-tags-input-group">
                            <input
                                type="text"
                                value={newTag}
                                onChange={(e) => setNewTag(e.target.value)}
                                onKeyPress={handleKeyPress}
                                placeholder={t('stories.basic.addTagPlaceholder')}
                                className="publication-tags-input"
                            />
                            <button
                                type="button"
                                onClick={addTag}
                                className="publication-tags-add-btn"
                                disabled={!newTag.trim()}
                            >
                                <FontAwesomeIcon icon={faPlus} />
                            </button>
                        </div>
                        {values.tags.length > 0 && (
                            <div className="publication-tags-list">
                                {values.tags.map((tag, index) => (
                                    <span key={index} className="publication-tag">
                                        {tag}
                                        <button
                                            type="button"
                                            onClick={() => removeTag(tag)}
                                            className="publication-tag-remove"
                                        >
                                            ×
                                        </button>
                                    </span>
                                ))}
                            </div>
                        )}
                    </div>
                </div>

                {/* Comments and Author Toggles - Side by Side */}
                <div className="publication-form-group">
                    <div className="publication-toggles-container">
                        {/* Comments Enabled */}
                        <div className="publication-toggle-item">
                            <div className="publication-comments-enabled-section">
                                <div className="publication-comments-enabled-header">
                                    <label className="publication-comments-enabled-label">
                                        <FontAwesomeIcon icon={faCommentDots} />
                                        {t('stories.settings.commentsEnabled')}
                                    </label>
                                    <div className="publication-comments-enabled-description">
                                        {t('stories.settings.commentsEnabledDescription')}
                                    </div>
                                </div>

                                <div className="publication-comments-toggle-container">
                                    <label className="publication-comments-toggle">
                                        <input
                                            type="checkbox"
                                            name="commentsEnabled"
                                            checked={values.commentsEnabled}
                                            onChange={onChangeHandler}
                                            className="publication-comments-toggle-input"
                                        />
                                        <span className="publication-comments-toggle-slider">
                                            <span className="publication-comments-toggle-thumb">
                                                <FontAwesomeIcon
                                                    icon={values.commentsEnabled ? faCheck : faTimes}
                                                    className="publication-comments-toggle-icon"
                                                />
                                            </span>
                                        </span>
                                        <span className="publication-comments-toggle-text">
                                            {values.commentsEnabled ? t('stories.settings.commentsAllowed') : t('stories.settings.commentsDisabled')}
                                        </span>
                                    </label>
                                </div>
                            </div>
                        </div>

                        {/* Show Author */}
                        <div className="publication-toggle-item">
                            <div className="publication-comments-enabled-section">
                                <div className="publication-comments-enabled-header">
                                    <label className="publication-comments-enabled-label">
                                        <FontAwesomeIcon icon={faUser} />
                                        {t('stories.basic.showAuthor')}
                                    </label>
                                    <div className="publication-comments-enabled-description">
                                        {t('stories.basic.showAuthorDescription')}
                                    </div>
                                </div>

                                <div className="publication-comments-toggle-container">
                                    <label className="publication-comments-toggle">
                                        <input
                                            type="checkbox"
                                            name="showAuthor"
                                            checked={values.showAuthor}
                                            onChange={onChangeHandler}
                                            className="publication-comments-toggle-input"
                                        />
                                        <span className="publication-comments-toggle-slider">
                                            <span className="publication-comments-toggle-thumb">
                                                <FontAwesomeIcon
                                                    icon={values.showAuthor ? faCheck : faTimes}
                                                    className="publication-comments-toggle-icon"
                                                />
                                            </span>
                                        </span>
                                        <span className="publication-comments-toggle-text">
                                            {values.showAuthor ? t('stories.basic.authorVisible') : t('stories.basic.authorHidden')}
                                        </span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {values.showAuthor && (
                    <>
                        {/* Author Name */}
                        <div className="publication-form-group">
                            <label htmlFor="author" className="publication-field-label">
                                <FontAwesomeIcon icon={faUser} />
                                {t('stories.basic.author')}
                            </label>
                            <input
                                type="text"
                                id="author"
                                name="author"
                                value={values.author || ''}
                                onChange={onChangeHandler}
                                placeholder={t('stories.basic.authorPlaceholder')}
                            />
                        </div>

                        {/* Author Email */}
                        <div className="publication-form-group">
                            <label htmlFor="authorEmail" className="publication-field-label">
                                <FontAwesomeIcon icon={faUser} />
                                {t('stories.basic.authorEmail')}
                            </label>
                            <input
                                type="email"
                                id="authorEmail"
                                name="authorEmail"
                                value={values.authorEmail || ''}
                                onChange={onChangeHandler}
                                placeholder={t('stories.basic.authorEmailPlaceholder')}
                            />
                        </div>

                        {/* Author Image */}
                        <div className="publication-form-group">
                            <label>
                                <FontAwesomeIcon icon={faImage} />
                                <span style={{ marginLeft: '0.5rem' }}>
                                    {t('stories.basic.authorImage')}
                                </span>
                            </label>
                            <div className="publication-sections-field-help">
                                {t('stories.helpTexts.authorImageHelp')}
                            </div>

                            <div className="publication-sections-image-upload">
                                {/* Upload methods */}
                                <div className="publication-sections-upload-methods">
                                    <div className="publication-sections-upload-method">
                                        <label className="publication-sections-upload-btn">
                                            <FontAwesomeIcon icon={faUpload} />
                                            {values.authorImage?.src ? t('stories.media.changeImage') : t('stories.media.uploadImage')}
                                            <input
                                                type="file"
                                                accept="image/*"
                                                onChange={handleAuthorImageUpload}
                                                style={{ display: 'none' }}
                                            />
                                        </label>
                                    </div>

                                    <div className="publication-sections-upload-method">
                                        <button
                                            type="button"
                                            className="publication-sections-upload-btn"
                                            onClick={() => setShowAuthorImageUrlInput(prev => !prev)}
                                        >
                                            <FontAwesomeIcon icon={faLink} />
                                            {values.authorImage?.src ? t('stories.media.changeImageUrl') : t('stories.media.addImageUrl')}
                                        </button>
                                    </div>

                                    {values.authorImage?.src && (
                                        <div className="publication-sections-upload-method">
                                            <button
                                                type="button"
                                                className="publication-sections-clear-btn"
                                                onClick={removeAuthorImage}
                                            >
                                                <FontAwesomeIcon icon={faTrash} />
                                                {t('stories.media.clearImage')}
                                            </button>
                                        </div>
                                    )}
                                </div>

                                {/* URL input section */}
                                {showAuthorImageUrlInput && (
                                    <div className="publication-sections-url-input-section">
                                        <input
                                            type="url"
                                            placeholder={t('stories.media.imageUrl')}
                                            value={authorImageUrl || ''}
                                            onChange={(e) => setAuthorImageUrl(e.target.value)}
                                            className="publication-sections-url-input"
                                        />
                                        <button
                                            type="button"
                                            className="publication-sections-url-add-btn"
                                            onClick={() => {
                                                if (authorImageUrl?.trim()) {
                                                    addAuthorImageFromUrl(authorImageUrl.trim());
                                                    setAuthorImageUrl('');
                                                    setShowAuthorImageUrlInput(false);
                                                }
                                            }}
                                            disabled={!authorImageUrl?.trim()}
                                        >
                                            <FontAwesomeIcon icon={faLink} />
                                            {t('stories.media.addImage')}
                                        </button>
                                    </div>
                                )}
                            </div>

                            {/* Author Image Preview with controls on the right */}
                            {values.authorImage?.src && (
                                <div className="publication-sections-image-preview">
                                    <div className="publication-sections-image-container">
                                        <div className="publication-sections-image-item">
                                            <div className="publication-sections-image-preview">
                                                <img src={values.authorImage.src} alt={values.authorImage.alt || 'Author image'} />
                                                <div className="publication-sections-image-overlay">
                                                    <button
                                                        type="button"
                                                        className="publication-sections-image-remove-btn"
                                                        onClick={removeAuthorImage}
                                                        title={t('stories.media.removeImage')}
                                                    >
                                                        <FontAwesomeIcon icon={faTrash} />
                                                    </button>
                                                </div>
                                                {values.authorImage.isUploading && (
                                                    <div className="publication-sections-image-uploading">
                                                        <div className="publication-sections-uploading-spinner"></div>
                                                    </div>
                                                )}
                                            </div>
                                        </div>

                                        {/* Controls on the right side */}
                                        <div className="publication-sections-image-controls">
                                            <div className="publication-sections-image-input-group">
                                                <label>{t('stories.media.altText')}:</label>
                                                <input
                                                    type="text"
                                                    placeholder={t('stories.media.imageDescription')}
                                                    value={values.authorImage.alt || ''}
                                                    onChange={(e) => updateAuthorImageAlt(e.target.value)}
                                                    className="publication-sections-image-input"
                                                    maxLength={100}
                                                />
                                                <div className="publication-sections-char-count">
                                                    {values.authorImage.alt?.length || 0}/100
                                                </div>
                                            </div>

                                            <div className="publication-sections-image-input-group">
                                                <label>{t('stories.media.caption')}:</label>
                                                <input
                                                    type="text"
                                                    placeholder={t('stories.media.imageCaption')}
                                                    value={values.authorImage.caption || ''}
                                                    onChange={(e) => updateAuthorImageCaption(e.target.value)}
                                                    className="publication-sections-image-input"
                                                    maxLength={150}
                                                />
                                                <div className="publication-sections-char-count">
                                                    {values.authorImage.caption?.length || 0}/150
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            )}
                        </div>
                    </>
                )}
            </div>
        </div>
    );
};

export default BasicInfoSection;
